// <auto-generated />
using System;
using ExposureTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ExposureTracker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ExposureTracker.Models.Insured", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("PolicyNumber")
                        .HasColumnType("text");

                    b.Property<string>("BordereauxYear")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CedantCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CedingCompany")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Certificate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClientID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateofBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PlanEffectiveDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ReinsuredNetAmountAtRisk")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ReinsuredNetAmountAtRiskPlan")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ReinsuredNetAmountAtRiskRiders")
                        .HasColumnType("numeric");

                    b.Property<string>("RetrocededNarPlan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RetrocededNarRider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubstandardRatingPlan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubstandardRatingRiders")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("SumAssured")
                        .HasColumnType("numeric");

                    b.Property<string>("TreatyCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id", "PolicyNumber");

                    b.ToTable("dbInsured");
                });

            modelBuilder.Entity("ExposureTracker.Models.PolicyNo", b =>
                {
                    b.Property<string>("PolicyNumber")
                        .HasColumnType("text");

                    b.HasKey("PolicyNumber");

                    b.ToTable("dbPolicy");
                });
#pragma warning restore 612, 618
        }
    }
}
